apiVersion: v1
kind: Service
metadata:
  name: gotest-service
spec:
  type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
  ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
  - name: http
    port: 9090
    targetPort: 8090
  selector:
    app: gotest